/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using SyncStorage.ApiClient.Client;
using SyncStorage.ApiClient.Model;

namespace SyncStorage.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompletionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Force completion of a test run
        /// </summary>
        /// <remarks>
        ///  Force processing completion for a specific test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>CompletionResponse</returns>
        CompletionResponse ForceCompletionGet(string testRunId);

        /// <summary>
        /// Force completion of a test run
        /// </summary>
        /// <remarks>
        ///  Force processing completion for a specific test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>ApiResponse of CompletionResponse</returns>
        ApiResponse<CompletionResponse> ForceCompletionGetWithHttpInfo(string testRunId);
        /// <summary>
        /// Wait for completion
        /// </summary>
        /// <remarks>
        ///  Wait until processing is completed for a test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>CompletionResponse</returns>
        CompletionResponse WaitCompletionGet(string testRunId);

        /// <summary>
        /// Wait for completion
        /// </summary>
        /// <remarks>
        ///  Wait until processing is completed for a test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>ApiResponse of CompletionResponse</returns>
        ApiResponse<CompletionResponse> WaitCompletionGetWithHttpInfo(string testRunId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompletionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Force completion of a test run
        /// </summary>
        /// <remarks>
        ///  Force processing completion for a specific test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompletionResponse</returns>
        System.Threading.Tasks.Task<CompletionResponse> ForceCompletionGetAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Force completion of a test run
        /// </summary>
        /// <remarks>
        ///  Force processing completion for a specific test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompletionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompletionResponse>> ForceCompletionGetWithHttpInfoAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Wait for completion
        /// </summary>
        /// <remarks>
        ///  Wait until processing is completed for a test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompletionResponse</returns>
        System.Threading.Tasks.Task<CompletionResponse> WaitCompletionGetAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Wait for completion
        /// </summary>
        /// <remarks>
        ///  Wait until processing is completed for a test run.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompletionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CompletionResponse>> WaitCompletionGetWithHttpInfoAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICompletionApi : ICompletionApiSync, ICompletionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CompletionApi : IDisposable, ICompletionApi
    {
        private SyncStorage.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public CompletionApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public CompletionApi(string basePath)
        {
            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                new SyncStorage.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public CompletionApi(SyncStorage.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CompletionApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CompletionApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                new SyncStorage.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CompletionApi(HttpClient client, SyncStorage.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CompletionApi(SyncStorage.ApiClient.Client.ISynchronousClient client, SyncStorage.ApiClient.Client.IAsynchronousClient asyncClient, SyncStorage.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public SyncStorage.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SyncStorage.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SyncStorage.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SyncStorage.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SyncStorage.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Force completion of a test run  Force processing completion for a specific test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>CompletionResponse</returns>
        public CompletionResponse ForceCompletionGet(string testRunId)
        {
            SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse> localVarResponse = ForceCompletionGetWithHttpInfo(testRunId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Force completion of a test run  Force processing completion for a specific test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>ApiResponse of CompletionResponse</returns>
        public SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse> ForceCompletionGetWithHttpInfo(string testRunId)
        {
            // verify the required parameter 'testRunId' is set
            if (testRunId == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'testRunId' when calling CompletionApi->ForceCompletionGet");

            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(SyncStorage.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "testRunId", testRunId));


            // make the HTTP request
            var localVarResponse = this.Client.Get<CompletionResponse>("/force-completion", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ForceCompletionGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Force completion of a test run  Force processing completion for a specific test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompletionResponse</returns>
        public async System.Threading.Tasks.Task<CompletionResponse> ForceCompletionGetAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default)
        {
            SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse> localVarResponse = await ForceCompletionGetWithHttpInfoAsync(testRunId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Force completion of a test run  Force processing completion for a specific test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompletionResponse)</returns>
        public async System.Threading.Tasks.Task<SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse>> ForceCompletionGetWithHttpInfoAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'testRunId' is set
            if (testRunId == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'testRunId' when calling CompletionApi->ForceCompletionGet");


            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(SyncStorage.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "testRunId", testRunId));


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CompletionResponse>("/force-completion", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ForceCompletionGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Wait for completion  Wait until processing is completed for a test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>CompletionResponse</returns>
        public CompletionResponse WaitCompletionGet(string testRunId)
        {
            SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse> localVarResponse = WaitCompletionGetWithHttpInfo(testRunId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Wait for completion  Wait until processing is completed for a test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <returns>ApiResponse of CompletionResponse</returns>
        public SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse> WaitCompletionGetWithHttpInfo(string testRunId)
        {
            // verify the required parameter 'testRunId' is set
            if (testRunId == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'testRunId' when calling CompletionApi->WaitCompletionGet");

            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(SyncStorage.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "testRunId", testRunId));


            // make the HTTP request
            var localVarResponse = this.Client.Get<CompletionResponse>("/wait-completion", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WaitCompletionGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Wait for completion  Wait until processing is completed for a test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CompletionResponse</returns>
        public async System.Threading.Tasks.Task<CompletionResponse> WaitCompletionGetAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default)
        {
            SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse> localVarResponse = await WaitCompletionGetWithHttpInfoAsync(testRunId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Wait for completion  Wait until processing is completed for a test run.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="testRunId">Test Run ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CompletionResponse)</returns>
        public async System.Threading.Tasks.Task<SyncStorage.ApiClient.Client.ApiResponse<CompletionResponse>> WaitCompletionGetWithHttpInfoAsync(string testRunId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'testRunId' is set
            if (testRunId == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'testRunId' when calling CompletionApi->WaitCompletionGet");


            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(SyncStorage.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "testRunId", testRunId));


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CompletionResponse>("/wait-completion", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WaitCompletionGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
