/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using SyncStorage.ApiClient.Client;
using SyncStorage.ApiClient.Model;

namespace SyncStorage.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Register a new worker
        /// </summary>
        /// <remarks>
        ///  Register a new worker with the sync storage service.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <returns>RegisterResponse</returns>
        RegisterResponse RegisterPost(RegisterRequest registerRequest);

        /// <summary>
        /// Register a new worker
        /// </summary>
        /// <remarks>
        ///  Register a new worker with the sync storage service.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <returns>ApiResponse of RegisterResponse</returns>
        ApiResponse<RegisterResponse> RegisterPostWithHttpInfo(RegisterRequest registerRequest);
        /// <summary>
        /// Set worker status
        /// </summary>
        /// <remarks>
        ///  Set the status of a worker by its PID.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <returns>SetWorkerStatusResponse</returns>
        SetWorkerStatusResponse SetWorkerStatusPost(SetWorkerStatusRequest setWorkerStatusRequest);

        /// <summary>
        /// Set worker status
        /// </summary>
        /// <remarks>
        ///  Set the status of a worker by its PID.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <returns>ApiResponse of SetWorkerStatusResponse</returns>
        ApiResponse<SetWorkerStatusResponse> SetWorkerStatusPostWithHttpInfo(SetWorkerStatusRequest setWorkerStatusRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Register a new worker
        /// </summary>
        /// <remarks>
        ///  Register a new worker with the sync storage service.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RegisterResponse</returns>
        System.Threading.Tasks.Task<RegisterResponse> RegisterPostAsync(RegisterRequest registerRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Register a new worker
        /// </summary>
        /// <remarks>
        ///  Register a new worker with the sync storage service.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RegisterResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RegisterResponse>> RegisterPostWithHttpInfoAsync(RegisterRequest registerRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Set worker status
        /// </summary>
        /// <remarks>
        ///  Set the status of a worker by its PID.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SetWorkerStatusResponse</returns>
        System.Threading.Tasks.Task<SetWorkerStatusResponse> SetWorkerStatusPostAsync(SetWorkerStatusRequest setWorkerStatusRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Set worker status
        /// </summary>
        /// <remarks>
        ///  Set the status of a worker by its PID.
        /// </remarks>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SetWorkerStatusResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SetWorkerStatusResponse>> SetWorkerStatusPostWithHttpInfoAsync(SetWorkerStatusRequest setWorkerStatusRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkersApi : IWorkersApiSync, IWorkersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WorkersApi : IDisposable, IWorkersApi
    {
        private SyncStorage.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public WorkersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public WorkersApi(string basePath)
        {
            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                new SyncStorage.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public WorkersApi(SyncStorage.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WorkersApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WorkersApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                new SyncStorage.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WorkersApi(HttpClient client, SyncStorage.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = SyncStorage.ApiClient.Client.Configuration.MergeConfigurations(
                SyncStorage.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new SyncStorage.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public WorkersApi(SyncStorage.ApiClient.Client.ISynchronousClient client, SyncStorage.ApiClient.Client.IAsynchronousClient asyncClient, SyncStorage.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SyncStorage.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public SyncStorage.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SyncStorage.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SyncStorage.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SyncStorage.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SyncStorage.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Register a new worker  Register a new worker with the sync storage service.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <returns>RegisterResponse</returns>
        public RegisterResponse RegisterPost(RegisterRequest registerRequest)
        {
            SyncStorage.ApiClient.Client.ApiResponse<RegisterResponse> localVarResponse = RegisterPostWithHttpInfo(registerRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Register a new worker  Register a new worker with the sync storage service.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <returns>ApiResponse of RegisterResponse</returns>
        public SyncStorage.ApiClient.Client.ApiResponse<RegisterResponse> RegisterPostWithHttpInfo(RegisterRequest registerRequest)
        {
            // verify the required parameter 'registerRequest' is set
            if (registerRequest == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'registerRequest' when calling WorkersApi->RegisterPost");

            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = registerRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<RegisterResponse>("/register", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RegisterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Register a new worker  Register a new worker with the sync storage service.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RegisterResponse</returns>
        public async System.Threading.Tasks.Task<RegisterResponse> RegisterPostAsync(RegisterRequest registerRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            SyncStorage.ApiClient.Client.ApiResponse<RegisterResponse> localVarResponse = await RegisterPostWithHttpInfoAsync(registerRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Register a new worker  Register a new worker with the sync storage service.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="registerRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RegisterResponse)</returns>
        public async System.Threading.Tasks.Task<SyncStorage.ApiClient.Client.ApiResponse<RegisterResponse>> RegisterPostWithHttpInfoAsync(RegisterRequest registerRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'registerRequest' is set
            if (registerRequest == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'registerRequest' when calling WorkersApi->RegisterPost");


            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = registerRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<RegisterResponse>("/register", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RegisterPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set worker status  Set the status of a worker by its PID.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <returns>SetWorkerStatusResponse</returns>
        public SetWorkerStatusResponse SetWorkerStatusPost(SetWorkerStatusRequest setWorkerStatusRequest)
        {
            SyncStorage.ApiClient.Client.ApiResponse<SetWorkerStatusResponse> localVarResponse = SetWorkerStatusPostWithHttpInfo(setWorkerStatusRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set worker status  Set the status of a worker by its PID.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <returns>ApiResponse of SetWorkerStatusResponse</returns>
        public SyncStorage.ApiClient.Client.ApiResponse<SetWorkerStatusResponse> SetWorkerStatusPostWithHttpInfo(SetWorkerStatusRequest setWorkerStatusRequest)
        {
            // verify the required parameter 'setWorkerStatusRequest' is set
            if (setWorkerStatusRequest == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'setWorkerStatusRequest' when calling WorkersApi->SetWorkerStatusPost");

            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/plain"
            };

            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = setWorkerStatusRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<SetWorkerStatusResponse>("/set_worker_status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetWorkerStatusPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set worker status  Set the status of a worker by its PID.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SetWorkerStatusResponse</returns>
        public async System.Threading.Tasks.Task<SetWorkerStatusResponse> SetWorkerStatusPostAsync(SetWorkerStatusRequest setWorkerStatusRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            SyncStorage.ApiClient.Client.ApiResponse<SetWorkerStatusResponse> localVarResponse = await SetWorkerStatusPostWithHttpInfoAsync(setWorkerStatusRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set worker status  Set the status of a worker by its PID.
        /// </summary>
        /// <exception cref="SyncStorage.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="setWorkerStatusRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SetWorkerStatusResponse)</returns>
        public async System.Threading.Tasks.Task<SyncStorage.ApiClient.Client.ApiResponse<SetWorkerStatusResponse>> SetWorkerStatusPostWithHttpInfoAsync(SetWorkerStatusRequest setWorkerStatusRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'setWorkerStatusRequest' is set
            if (setWorkerStatusRequest == null)
                throw new SyncStorage.ApiClient.Client.ApiException(400, "Missing required parameter 'setWorkerStatusRequest' when calling WorkersApi->SetWorkerStatusPost");


            SyncStorage.ApiClient.Client.RequestOptions localVarRequestOptions = new SyncStorage.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/plain"
            };


            var localVarContentType = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SyncStorage.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = setWorkerStatusRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SetWorkerStatusResponse>("/set_worker_status", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetWorkerStatusPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
