/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Polly;
using System.Net.Http;

namespace SyncStorage.ApiClient.Client
{
    /// <summary>
    /// Configuration class to set the polly retry policies to be applied to the requests.
    /// </summary>
    public static class RetryConfiguration
    {
        /// <summary>
        /// Retry policy
        /// </summary>
        public static ISyncPolicy<HttpResponseMessage> RetryPolicy { get; set; }

        /// <summary>
        /// Async retry policy
        /// </summary>
        public static IAsyncPolicy<HttpResponseMessage> AsyncRetryPolicy { get; set; }
    }
}
