/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = SyncStorage.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = SyncStorage.ApiClient.Client.OpenAPIDateConverter;

namespace SyncStorage.ApiClient.Model
{
    /// <summary>
    /// HealthStatusResponse
    /// </summary>
    [DataContract(Name = "HealthStatusResponse")]
    public partial class HealthStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthStatusResponse" /> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="lastUpdate">lastUpdate.</param>
        public HealthStatusResponse(string status = default, DateTime lastUpdate = default)
        {
            this.Status = status;
            this.LastUpdate = lastUpdate;
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /*
        <example>ok</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets LastUpdate
        /// </summary>
        /*
        <example>2026-02-19T19:00Z</example>
        */
        [DataMember(Name = "last_update", EmitDefaultValue = false)]
        public DateTime LastUpdate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HealthStatusResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
