/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = SyncStorage.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = SyncStorage.ApiClient.Client.OpenAPIDateConverter;

namespace SyncStorage.ApiClient.Model
{
    /// <summary>
    /// RegisterResponse
    /// </summary>
    [DataContract(Name = "RegisterResponse")]
    public partial class RegisterResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterResponse" /> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="message">message.</param>
        /// <param name="pid">pid.</param>
        /// <param name="testRunId">testRunId.</param>
        /// <param name="isMaster">isMaster.</param>
        public RegisterResponse(string status = default, string message = default, string pid = default, string testRunId = default, bool isMaster = default)
        {
            this.Status = status;
            this.Message = message;
            this.Pid = pid;
            this.TestRunId = testRunId;
            this.IsMaster = isMaster;
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /*
        <example>ok</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /*
        <example>Worker registered successfully</example>
        */
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Pid
        /// </summary>
        /*
        <example>worker-12345-1234567890</example>
        */
        [DataMember(Name = "pid", EmitDefaultValue = false)]
        public string Pid { get; set; }

        /// <summary>
        /// Gets or Sets TestRunId
        /// </summary>
        /*
        <example>test-run-uuid</example>
        */
        [DataMember(Name = "testRunId", EmitDefaultValue = false)]
        public string TestRunId { get; set; }

        /// <summary>
        /// Gets or Sets IsMaster
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "is_master", EmitDefaultValue = true)]
        public bool IsMaster { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegisterResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Pid: ").Append(Pid).Append("\n");
            sb.Append("  TestRunId: ").Append(TestRunId).Append("\n");
            sb.Append("  IsMaster: ").Append(IsMaster).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
