/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = SyncStorage.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = SyncStorage.ApiClient.Client.OpenAPIDateConverter;

namespace SyncStorage.ApiClient.Model
{
    /// <summary>
    /// RegisterRequest
    /// </summary>
    [DataContract(Name = "RegisterRequest")]
    public partial class RegisterRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterRequest" /> class.
        /// </summary>
        /// <param name="pid">pid.</param>
        /// <param name="testRunId">testRunId.</param>
        /// <param name="baseUrl">baseUrl.</param>
        /// <param name="privateToken">privateToken.</param>
        public RegisterRequest(string pid = default, string testRunId = default, string baseUrl = default, string privateToken = default)
        {
            this.Pid = pid;
            this.TestRunId = testRunId;
            this.BaseUrl = baseUrl;
            this.PrivateToken = privateToken;
        }

        /// <summary>
        /// Gets or Sets Pid
        /// </summary>
        /*
        <example>worker-12345-1234567890</example>
        */
        [DataMember(Name = "pid", EmitDefaultValue = false)]
        public string Pid { get; set; }

        /// <summary>
        /// Gets or Sets TestRunId
        /// </summary>
        /*
        <example>test-run-uuid</example>
        */
        [DataMember(Name = "testRunId", EmitDefaultValue = false)]
        public string TestRunId { get; set; }

        /// <summary>
        /// Gets or Sets BaseUrl
        /// </summary>
        /*
        <example>https://example.com</example>
        */
        [DataMember(Name = "baseUrl", EmitDefaultValue = false)]
        public string BaseUrl { get; set; }

        /// <summary>
        /// Gets or Sets PrivateToken
        /// </summary>
        /*
        <example>xxxxxxxxxxxxxx</example>
        */
        [DataMember(Name = "privateToken", EmitDefaultValue = false)]
        public string PrivateToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegisterRequest {\n");
            sb.Append("  Pid: ").Append(Pid).Append("\n");
            sb.Append("  TestRunId: ").Append(TestRunId).Append("\n");
            sb.Append("  BaseUrl: ").Append(BaseUrl).Append("\n");
            sb.Append("  PrivateToken: ").Append(PrivateToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
