/*
 * Sync Storage Service API
 *
 * This is a sync storage service for coordinating test workers.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = SyncStorage.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = SyncStorage.ApiClient.Client.OpenAPIDateConverter;

namespace SyncStorage.ApiClient.Model
{
    /// <summary>
    /// TestResultCutApiModel
    /// </summary>
    [DataContract(Name = "TestResultCutApiModel")]
    public partial class TestResultCutApiModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResultCutApiModel" /> class.
        /// </summary>
        /// <param name="projectId">projectId.</param>
        /// <param name="autoTestExternalId">autoTestExternalId.</param>
        /// <param name="statusCode">statusCode.</param>
        /// <param name="statusType">statusType.</param>
        /// <param name="startedOn">startedOn.</param>
        public TestResultCutApiModel(string projectId = default, string autoTestExternalId = default, string statusCode = default, string statusType = default, DateTime? startedOn = default)
        {
            this.ProjectId = projectId;
            this.AutoTestExternalId = autoTestExternalId;
            this.StatusCode = statusCode;
            this.StatusType = statusType;
            this.StartedOn = startedOn;
        }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        /*
        <example>019581fa-3d2d-7682-b587-fcd508d42b9f</example>
        */
        [DataMember(Name = "projectId", EmitDefaultValue = false)]
        public string ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets AutoTestExternalId
        /// </summary>
        /*
        <example>test-123</example>
        */
        [DataMember(Name = "autoTestExternalId", EmitDefaultValue = false)]
        public string AutoTestExternalId { get; set; }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>
        /*
        <example>Passed</example>
        */
        [DataMember(Name = "statusCode", EmitDefaultValue = false)]
        public string StatusCode { get; set; }

        /// <summary>
        /// Gets or Sets StatusType
        /// </summary>
        /*
        <example>Succeeded</example>
        */
        [DataMember(Name = "statusType", EmitDefaultValue = false)]
        public string StatusType { get; set; }

        /// <summary>
        /// Gets or Sets StartedOn
        /// </summary>
        /*
        <example>2026-02-19T19:00Z</example>
        */
        [DataMember(Name = "startedOn", EmitDefaultValue = true)]
        public DateTime? StartedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestResultCutApiModel {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  AutoTestExternalId: ").Append(AutoTestExternalId).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  StatusType: ").Append(StatusType).Append("\n");
            sb.Append("  StartedOn: ").Append(StartedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
