/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// CreateStepApiModel
    /// </summary>
    [DataContract(Name = "CreateStepApiModel")]
    public partial class CreateStepApiModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateStepApiModel" /> class.
        /// </summary>
        /// <param name="action">action.</param>
        /// <param name="expected">expected.</param>
        /// <param name="testData">testData.</param>
        /// <param name="comments">comments.</param>
        /// <param name="workItemId">workItemId.</param>
        public CreateStepApiModel(string action = default, string expected = default, string testData = default, string comments = default, Guid? workItemId = default)
        {
            this.Action = action;
            this.Expected = expected;
            this.TestData = testData;
            this.Comments = comments;
            this.WorkItemId = workItemId;
        }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name = "action", EmitDefaultValue = true)]
        public string Action { get; set; }

        /// <summary>
        /// Gets or Sets Expected
        /// </summary>
        [DataMember(Name = "expected", EmitDefaultValue = true)]
        public string Expected { get; set; }

        /// <summary>
        /// Gets or Sets TestData
        /// </summary>
        [DataMember(Name = "testData", EmitDefaultValue = true)]
        public string TestData { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name = "comments", EmitDefaultValue = true)]
        public string Comments { get; set; }

        /// <summary>
        /// Gets or Sets WorkItemId
        /// </summary>
        [DataMember(Name = "workItemId", EmitDefaultValue = true)]
        public Guid? WorkItemId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateStepApiModel {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Expected: ").Append(Expected).Append("\n");
            sb.Append("  TestData: ").Append(TestData).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  WorkItemId: ").Append(WorkItemId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
