/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// TestResultShortResponse
    /// </summary>
    [DataContract(Name = "TestResultShortResponse")]
    public partial class TestResultShortResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResultShortResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestResultShortResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResultShortResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="autotestExternalId">autotestExternalId.</param>
        /// <param name="autoTestTags">autoTestTags (required).</param>
        /// <param name="testRunId">testRunId (required).</param>
        /// <param name="configurationId">configurationId (required).</param>
        /// <param name="configurationName">configurationName (required).</param>
        /// <param name="outcome">outcome.</param>
        /// <param name="status">status (required).</param>
        /// <param name="resultReasons">resultReasons (required).</param>
        /// <param name="comment">comment.</param>
        /// <param name="duration">duration.</param>
        /// <param name="links">links (required).</param>
        /// <param name="attachments">attachments (required).</param>
        /// <param name="rerunCompletedCount">rerunCompletedCount (required).</param>
        public TestResultShortResponse(Guid id = default, string name = default, string autotestExternalId = default, List<string> autoTestTags = default, Guid testRunId = default, Guid configurationId = default, string configurationName = default, string outcome = default, TestStatusApiResult status = default, List<AutoTestResultReasonShort> resultReasons = default, string comment = default, long? duration = default, List<TestResultLinkApiResult> links = default, List<AttachmentApiResult> attachments = default, int rerunCompletedCount = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for TestResultShortResponse and cannot be null");
            }
            this.Name = name;
            // to ensure "autoTestTags" is required (not null)
            if (autoTestTags == null)
            {
                throw new ArgumentNullException("autoTestTags is a required property for TestResultShortResponse and cannot be null");
            }
            this.AutoTestTags = autoTestTags;
            this.TestRunId = testRunId;
            this.ConfigurationId = configurationId;
            // to ensure "configurationName" is required (not null)
            if (configurationName == null)
            {
                throw new ArgumentNullException("configurationName is a required property for TestResultShortResponse and cannot be null");
            }
            this.ConfigurationName = configurationName;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for TestResultShortResponse and cannot be null");
            }
            this.Status = status;
            // to ensure "resultReasons" is required (not null)
            if (resultReasons == null)
            {
                throw new ArgumentNullException("resultReasons is a required property for TestResultShortResponse and cannot be null");
            }
            this.ResultReasons = resultReasons;
            // to ensure "links" is required (not null)
            if (links == null)
            {
                throw new ArgumentNullException("links is a required property for TestResultShortResponse and cannot be null");
            }
            this.Links = links;
            // to ensure "attachments" is required (not null)
            if (attachments == null)
            {
                throw new ArgumentNullException("attachments is a required property for TestResultShortResponse and cannot be null");
            }
            this.Attachments = attachments;
            this.RerunCompletedCount = rerunCompletedCount;
            this.AutotestExternalId = autotestExternalId;
            this.Outcome = outcome;
            this.Comment = comment;
            this.Duration = duration;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets AutotestExternalId
        /// </summary>
        [DataMember(Name = "autotestExternalId", EmitDefaultValue = true)]
        public string AutotestExternalId { get; set; }

        /// <summary>
        /// Gets or Sets AutoTestTags
        /// </summary>
        [DataMember(Name = "autoTestTags", IsRequired = true, EmitDefaultValue = true)]
        public List<string> AutoTestTags { get; set; }

        /// <summary>
        /// Gets or Sets TestRunId
        /// </summary>
        [DataMember(Name = "testRunId", IsRequired = true, EmitDefaultValue = true)]
        public Guid TestRunId { get; set; }

        /// <summary>
        /// Gets or Sets ConfigurationId
        /// </summary>
        [DataMember(Name = "configurationId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ConfigurationId { get; set; }

        /// <summary>
        /// Gets or Sets ConfigurationName
        /// </summary>
        [DataMember(Name = "configurationName", IsRequired = true, EmitDefaultValue = true)]
        public string ConfigurationName { get; set; }

        /// <summary>
        /// Gets or Sets Outcome
        /// </summary>
        [DataMember(Name = "outcome", EmitDefaultValue = true)]
        [Obsolete]
        public string Outcome { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public TestStatusApiResult Status { get; set; }

        /// <summary>
        /// Gets or Sets ResultReasons
        /// </summary>
        [DataMember(Name = "resultReasons", IsRequired = true, EmitDefaultValue = true)]
        public List<AutoTestResultReasonShort> ResultReasons { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = true)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public long? Duration { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public List<TestResultLinkApiResult> Links { get; set; }

        /// <summary>
        /// Gets or Sets Attachments
        /// </summary>
        [DataMember(Name = "attachments", IsRequired = true, EmitDefaultValue = true)]
        public List<AttachmentApiResult> Attachments { get; set; }

        /// <summary>
        /// Gets or Sets RerunCompletedCount
        /// </summary>
        [DataMember(Name = "rerunCompletedCount", IsRequired = true, EmitDefaultValue = true)]
        public int RerunCompletedCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestResultShortResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AutotestExternalId: ").Append(AutotestExternalId).Append("\n");
            sb.Append("  AutoTestTags: ").Append(AutoTestTags).Append("\n");
            sb.Append("  TestRunId: ").Append(TestRunId).Append("\n");
            sb.Append("  ConfigurationId: ").Append(ConfigurationId).Append("\n");
            sb.Append("  ConfigurationName: ").Append(ConfigurationName).Append("\n");
            sb.Append("  Outcome: ").Append(Outcome).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ResultReasons: ").Append(ResultReasons).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  RerunCompletedCount: ").Append(RerunCompletedCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
