/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// TestResultsFilterApiModel
    /// </summary>
    [DataContract(Name = "TestResultsFilterApiModel")]
    public partial class TestResultsFilterApiModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResultsFilterApiModel" /> class.
        /// </summary>
        /// <param name="configurationIds">configurationIds.</param>
        /// <param name="outcomes">outcomes.</param>
        /// <param name="statusCodes">statusCodes.</param>
        /// <param name="statusTypes">statusTypes.</param>
        /// <param name="varNamespace">varNamespace.</param>
        /// <param name="className">className.</param>
        /// <param name="autoTestGlobalIds">autoTestGlobalIds.</param>
        /// <param name="autoTestTags">autoTestTags.</param>
        /// <param name="excludeAutoTestTags">excludeAutoTestTags.</param>
        /// <param name="name">name.</param>
        /// <param name="duration">duration.</param>
        /// <param name="testRunIds">testRunIds.</param>
        public TestResultsFilterApiModel(List<Guid> configurationIds = default, List<TestResultOutcome> outcomes = default, List<string> statusCodes = default, List<TestStatusApiType> statusTypes = default, string varNamespace = default, string className = default, List<long> autoTestGlobalIds = default, List<string> autoTestTags = default, List<string> excludeAutoTestTags = default, string name = default, Int64RangeSelectorModel duration = default, List<Guid> testRunIds = default)
        {
            this.ConfigurationIds = configurationIds;
            this.Outcomes = outcomes;
            this.StatusCodes = statusCodes;
            this.StatusTypes = statusTypes;
            this.Namespace = varNamespace;
            this.ClassName = className;
            this.AutoTestGlobalIds = autoTestGlobalIds;
            this.AutoTestTags = autoTestTags;
            this.ExcludeAutoTestTags = excludeAutoTestTags;
            this.Name = name;
            this.Duration = duration;
            this.TestRunIds = testRunIds;
        }

        /// <summary>
        /// Gets or Sets ConfigurationIds
        /// </summary>
        [DataMember(Name = "configurationIds", EmitDefaultValue = true)]
        public List<Guid> ConfigurationIds { get; set; }

        /// <summary>
        /// Gets or Sets Outcomes
        /// </summary>
        [DataMember(Name = "outcomes", EmitDefaultValue = true)]
        [Obsolete]
        public List<TestResultOutcome> Outcomes { get; set; }

        /// <summary>
        /// Gets or Sets StatusCodes
        /// </summary>
        [DataMember(Name = "statusCodes", EmitDefaultValue = true)]
        public List<string> StatusCodes { get; set; }

        /// <summary>
        /// Gets or Sets StatusTypes
        /// </summary>
        [DataMember(Name = "statusTypes", EmitDefaultValue = true)]
        public List<TestStatusApiType> StatusTypes { get; set; }

        /// <summary>
        /// Gets or Sets Namespace
        /// </summary>
        [DataMember(Name = "namespace", EmitDefaultValue = true)]
        public string Namespace { get; set; }

        /// <summary>
        /// Gets or Sets ClassName
        /// </summary>
        [DataMember(Name = "className", EmitDefaultValue = true)]
        public string ClassName { get; set; }

        /// <summary>
        /// Gets or Sets AutoTestGlobalIds
        /// </summary>
        [DataMember(Name = "autoTestGlobalIds", EmitDefaultValue = true)]
        public List<long> AutoTestGlobalIds { get; set; }

        /// <summary>
        /// Gets or Sets AutoTestTags
        /// </summary>
        [DataMember(Name = "autoTestTags", EmitDefaultValue = true)]
        public List<string> AutoTestTags { get; set; }

        /// <summary>
        /// Gets or Sets ExcludeAutoTestTags
        /// </summary>
        [DataMember(Name = "excludeAutoTestTags", EmitDefaultValue = true)]
        public List<string> ExcludeAutoTestTags { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public Int64RangeSelectorModel Duration { get; set; }

        /// <summary>
        /// Gets or Sets TestRunIds
        /// </summary>
        [DataMember(Name = "testRunIds", EmitDefaultValue = true)]
        public List<Guid> TestRunIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestResultsFilterApiModel {\n");
            sb.Append("  ConfigurationIds: ").Append(ConfigurationIds).Append("\n");
            sb.Append("  Outcomes: ").Append(Outcomes).Append("\n");
            sb.Append("  StatusCodes: ").Append(StatusCodes).Append("\n");
            sb.Append("  StatusTypes: ").Append(StatusTypes).Append("\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("  ClassName: ").Append(ClassName).Append("\n");
            sb.Append("  AutoTestGlobalIds: ").Append(AutoTestGlobalIds).Append("\n");
            sb.Append("  AutoTestTags: ").Append(AutoTestTags).Append("\n");
            sb.Append("  ExcludeAutoTestTags: ").Append(ExcludeAutoTestTags).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  TestRunIds: ").Append(TestRunIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Namespace (string) maxLength
            if (this.Namespace != null && this.Namespace.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be less than 255.", new [] { "Namespace" });
            }

            // Namespace (string) minLength
            if (this.Namespace != null && this.Namespace.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Namespace, length must be greater than 0.", new [] { "Namespace" });
            }

            // ClassName (string) maxLength
            if (this.ClassName != null && this.ClassName.Length > 255)
            {
                yield return new ValidationResult("Invalid value for ClassName, length must be less than 255.", new [] { "ClassName" });
            }

            // ClassName (string) minLength
            if (this.ClassName != null && this.ClassName.Length < 0)
            {
                yield return new ValidationResult("Invalid value for ClassName, length must be greater than 0.", new [] { "ClassName" });
            }

            yield break;
        }
    }

}
