/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// WorkItemApiResult
    /// </summary>
    [DataContract(Name = "WorkItemApiResult")]
    public partial class WorkItemApiResult : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets EntityTypeName
        /// </summary>
        [DataMember(Name = "entityTypeName", IsRequired = true, EmitDefaultValue = true)]
        public WorkItemEntityTypeApiModel EntityTypeName { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public WorkItemStateApiModel State { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name = "priority", IsRequired = true, EmitDefaultValue = true)]
        public WorkItemPriorityApiModel Priority { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkItemApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemApiResult" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="globalId">globalId (required).</param>
        /// <param name="projectId">projectId (required).</param>
        /// <param name="sectionId">sectionId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="description">description.</param>
        /// <param name="entityTypeName">entityTypeName (required).</param>
        /// <param name="duration">duration (required).</param>
        /// <param name="state">state (required).</param>
        /// <param name="priority">priority (required).</param>
        /// <param name="isAutomated">isAutomated (required).</param>
        /// <param name="attributes">attributes (required).</param>
        /// <param name="tags">tags (required).</param>
        /// <param name="sectionPreconditionSteps">sectionPreconditionSteps (required).</param>
        /// <param name="sectionPostconditionSteps">sectionPostconditionSteps (required).</param>
        /// <param name="preconditionSteps">preconditionSteps (required).</param>
        /// <param name="steps">steps (required).</param>
        /// <param name="postconditionSteps">postconditionSteps (required).</param>
        /// <param name="iterations">iterations (required).</param>
        /// <param name="autoTests">autoTests (required).</param>
        /// <param name="attachments">attachments (required).</param>
        /// <param name="links">links (required).</param>
        /// <param name="parameters">parameters (required).</param>
        /// <param name="isDeleted">isDeleted (required).</param>
        public WorkItemApiResult(Guid id = default, long globalId = default, Guid projectId = default, Guid sectionId = default, string name = default, string description = default, WorkItemEntityTypeApiModel entityTypeName = default, int duration = default, WorkItemStateApiModel state = default, WorkItemPriorityApiModel priority = default, bool isAutomated = default, Dictionary<string, Object> attributes = default, List<TagModel> tags = default, List<StepModel> sectionPreconditionSteps = default, List<StepModel> sectionPostconditionSteps = default, List<StepModel> preconditionSteps = default, List<StepModel> steps = default, List<StepModel> postconditionSteps = default, List<IterationModel> iterations = default, List<AutoTestModel> autoTests = default, List<AttachmentModel> attachments = default, List<LinkModel> links = default, List<WorkItemParameterKeyApiResult> parameters = default, bool isDeleted = default)
        {
            this.Id = id;
            this.GlobalId = globalId;
            this.ProjectId = projectId;
            this.SectionId = sectionId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for WorkItemApiResult and cannot be null");
            }
            this.Name = name;
            this.EntityTypeName = entityTypeName;
            this.Duration = duration;
            this.State = state;
            this.Priority = priority;
            this.IsAutomated = isAutomated;
            // to ensure "attributes" is required (not null)
            if (attributes == null)
            {
                throw new ArgumentNullException("attributes is a required property for WorkItemApiResult and cannot be null");
            }
            this.Attributes = attributes;
            // to ensure "tags" is required (not null)
            if (tags == null)
            {
                throw new ArgumentNullException("tags is a required property for WorkItemApiResult and cannot be null");
            }
            this.Tags = tags;
            // to ensure "sectionPreconditionSteps" is required (not null)
            if (sectionPreconditionSteps == null)
            {
                throw new ArgumentNullException("sectionPreconditionSteps is a required property for WorkItemApiResult and cannot be null");
            }
            this.SectionPreconditionSteps = sectionPreconditionSteps;
            // to ensure "sectionPostconditionSteps" is required (not null)
            if (sectionPostconditionSteps == null)
            {
                throw new ArgumentNullException("sectionPostconditionSteps is a required property for WorkItemApiResult and cannot be null");
            }
            this.SectionPostconditionSteps = sectionPostconditionSteps;
            // to ensure "preconditionSteps" is required (not null)
            if (preconditionSteps == null)
            {
                throw new ArgumentNullException("preconditionSteps is a required property for WorkItemApiResult and cannot be null");
            }
            this.PreconditionSteps = preconditionSteps;
            // to ensure "steps" is required (not null)
            if (steps == null)
            {
                throw new ArgumentNullException("steps is a required property for WorkItemApiResult and cannot be null");
            }
            this.Steps = steps;
            // to ensure "postconditionSteps" is required (not null)
            if (postconditionSteps == null)
            {
                throw new ArgumentNullException("postconditionSteps is a required property for WorkItemApiResult and cannot be null");
            }
            this.PostconditionSteps = postconditionSteps;
            // to ensure "iterations" is required (not null)
            if (iterations == null)
            {
                throw new ArgumentNullException("iterations is a required property for WorkItemApiResult and cannot be null");
            }
            this.Iterations = iterations;
            // to ensure "autoTests" is required (not null)
            if (autoTests == null)
            {
                throw new ArgumentNullException("autoTests is a required property for WorkItemApiResult and cannot be null");
            }
            this.AutoTests = autoTests;
            // to ensure "attachments" is required (not null)
            if (attachments == null)
            {
                throw new ArgumentNullException("attachments is a required property for WorkItemApiResult and cannot be null");
            }
            this.Attachments = attachments;
            // to ensure "links" is required (not null)
            if (links == null)
            {
                throw new ArgumentNullException("links is a required property for WorkItemApiResult and cannot be null");
            }
            this.Links = links;
            // to ensure "parameters" is required (not null)
            if (parameters == null)
            {
                throw new ArgumentNullException("parameters is a required property for WorkItemApiResult and cannot be null");
            }
            this.Parameters = parameters;
            this.IsDeleted = isDeleted;
            this.Description = description;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets GlobalId
        /// </summary>
        [DataMember(Name = "globalId", IsRequired = true, EmitDefaultValue = true)]
        public long GlobalId { get; set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [DataMember(Name = "projectId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets SectionId
        /// </summary>
        [DataMember(Name = "sectionId", IsRequired = true, EmitDefaultValue = true)]
        public Guid SectionId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", IsRequired = true, EmitDefaultValue = true)]
        public int Duration { get; set; }

        /// <summary>
        /// Gets or Sets IsAutomated
        /// </summary>
        [DataMember(Name = "isAutomated", IsRequired = true, EmitDefaultValue = true)]
        public bool IsAutomated { get; set; }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name = "attributes", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Attributes { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", IsRequired = true, EmitDefaultValue = true)]
        public List<TagModel> Tags { get; set; }

        /// <summary>
        /// Gets or Sets SectionPreconditionSteps
        /// </summary>
        [DataMember(Name = "sectionPreconditionSteps", IsRequired = true, EmitDefaultValue = true)]
        public List<StepModel> SectionPreconditionSteps { get; set; }

        /// <summary>
        /// Gets or Sets SectionPostconditionSteps
        /// </summary>
        [DataMember(Name = "sectionPostconditionSteps", IsRequired = true, EmitDefaultValue = true)]
        public List<StepModel> SectionPostconditionSteps { get; set; }

        /// <summary>
        /// Gets or Sets PreconditionSteps
        /// </summary>
        [DataMember(Name = "preconditionSteps", IsRequired = true, EmitDefaultValue = true)]
        public List<StepModel> PreconditionSteps { get; set; }

        /// <summary>
        /// Gets or Sets Steps
        /// </summary>
        [DataMember(Name = "steps", IsRequired = true, EmitDefaultValue = true)]
        public List<StepModel> Steps { get; set; }

        /// <summary>
        /// Gets or Sets PostconditionSteps
        /// </summary>
        [DataMember(Name = "postconditionSteps", IsRequired = true, EmitDefaultValue = true)]
        public List<StepModel> PostconditionSteps { get; set; }

        /// <summary>
        /// Gets or Sets Iterations
        /// </summary>
        [DataMember(Name = "iterations", IsRequired = true, EmitDefaultValue = true)]
        public List<IterationModel> Iterations { get; set; }

        /// <summary>
        /// Gets or Sets AutoTests
        /// </summary>
        [DataMember(Name = "autoTests", IsRequired = true, EmitDefaultValue = true)]
        public List<AutoTestModel> AutoTests { get; set; }

        /// <summary>
        /// Gets or Sets Attachments
        /// </summary>
        [DataMember(Name = "attachments", IsRequired = true, EmitDefaultValue = true)]
        public List<AttachmentModel> Attachments { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public List<LinkModel> Links { get; set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [DataMember(Name = "parameters", IsRequired = true, EmitDefaultValue = true)]
        public List<WorkItemParameterKeyApiResult> Parameters { get; set; }

        /// <summary>
        /// Gets or Sets IsDeleted
        /// </summary>
        [DataMember(Name = "isDeleted", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkItemApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  GlobalId: ").Append(GlobalId).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  SectionId: ").Append(SectionId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EntityTypeName: ").Append(EntityTypeName).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  IsAutomated: ").Append(IsAutomated).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  SectionPreconditionSteps: ").Append(SectionPreconditionSteps).Append("\n");
            sb.Append("  SectionPostconditionSteps: ").Append(SectionPostconditionSteps).Append("\n");
            sb.Append("  PreconditionSteps: ").Append(PreconditionSteps).Append("\n");
            sb.Append("  Steps: ").Append(Steps).Append("\n");
            sb.Append("  PostconditionSteps: ").Append(PostconditionSteps).Append("\n");
            sb.Append("  Iterations: ").Append(Iterations).Append("\n");
            sb.Append("  AutoTests: ").Append(AutoTests).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
