/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// WorkItemFilterApiModel
    /// </summary>
    [DataContract(Name = "WorkItemFilterApiModel")]
    public partial class WorkItemFilterApiModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemFilterApiModel" /> class.
        /// </summary>
        /// <param name="nameOrId">nameOrId.</param>
        /// <param name="includeIds">includeIds.</param>
        /// <param name="excludeIds">excludeIds.</param>
        /// <param name="projectIds">projectIds.</param>
        /// <param name="name">name.</param>
        /// <param name="ids">ids.</param>
        /// <param name="globalIds">globalIds.</param>
        /// <param name="attributes">attributes.</param>
        /// <param name="isDeleted">isDeleted.</param>
        /// <param name="sectionIds">sectionIds.</param>
        /// <param name="states">states.</param>
        /// <param name="priorities">priorities.</param>
        /// <param name="sourceTypes">sourceTypes.</param>
        /// <param name="types">types.</param>
        /// <param name="duration">duration.</param>
        /// <param name="isAutomated">isAutomated.</param>
        /// <param name="tags">tags.</param>
        /// <param name="excludeTags">excludeTags.</param>
        /// <param name="autoTestIds">autoTestIds.</param>
        public WorkItemFilterApiModel(string nameOrId = default, List<Guid> includeIds = default, List<Guid> excludeIds = default, List<Guid> projectIds = default, string name = default, List<Guid> ids = default, List<long> globalIds = default, Dictionary<string, List<string>> attributes = default, bool? isDeleted = default, List<Guid> sectionIds = default, List<WorkItemStates> states = default, List<WorkItemPriorityModel> priorities = default, List<WorkItemSourceTypeModel> sourceTypes = default, List<WorkItemTypeModel> types = default, Int32RangeSelectorModel duration = default, bool? isAutomated = default, List<string> tags = default, List<string> excludeTags = default, List<Guid> autoTestIds = default)
        {
            this.NameOrId = nameOrId;
            this.IncludeIds = includeIds;
            this.ExcludeIds = excludeIds;
            this.ProjectIds = projectIds;
            this.Name = name;
            this.Ids = ids;
            this.GlobalIds = globalIds;
            this.Attributes = attributes;
            this.IsDeleted = isDeleted;
            this.SectionIds = sectionIds;
            this.States = states;
            this.Priorities = priorities;
            this.SourceTypes = sourceTypes;
            this.Types = types;
            this.Duration = duration;
            this.IsAutomated = isAutomated;
            this.Tags = tags;
            this.ExcludeTags = excludeTags;
            this.AutoTestIds = autoTestIds;
        }

        /// <summary>
        /// Gets or Sets NameOrId
        /// </summary>
        [DataMember(Name = "nameOrId", EmitDefaultValue = true)]
        public string NameOrId { get; set; }

        /// <summary>
        /// Gets or Sets IncludeIds
        /// </summary>
        [DataMember(Name = "includeIds", EmitDefaultValue = true)]
        public List<Guid> IncludeIds { get; set; }

        /// <summary>
        /// Gets or Sets ExcludeIds
        /// </summary>
        [DataMember(Name = "excludeIds", EmitDefaultValue = true)]
        public List<Guid> ExcludeIds { get; set; }

        /// <summary>
        /// Gets or Sets ProjectIds
        /// </summary>
        [DataMember(Name = "projectIds", EmitDefaultValue = true)]
        public List<Guid> ProjectIds { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Ids
        /// </summary>
        [DataMember(Name = "ids", EmitDefaultValue = true)]
        public List<Guid> Ids { get; set; }

        /// <summary>
        /// Gets or Sets GlobalIds
        /// </summary>
        [DataMember(Name = "globalIds", EmitDefaultValue = true)]
        public List<long> GlobalIds { get; set; }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name = "attributes", EmitDefaultValue = true)]
        public Dictionary<string, List<string>> Attributes { get; set; }

        /// <summary>
        /// Gets or Sets IsDeleted
        /// </summary>
        [DataMember(Name = "isDeleted", EmitDefaultValue = true)]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// Gets or Sets SectionIds
        /// </summary>
        [DataMember(Name = "sectionIds", EmitDefaultValue = true)]
        public List<Guid> SectionIds { get; set; }

        /// <summary>
        /// Gets or Sets States
        /// </summary>
        [DataMember(Name = "states", EmitDefaultValue = true)]
        public List<WorkItemStates> States { get; set; }

        /// <summary>
        /// Gets or Sets Priorities
        /// </summary>
        [DataMember(Name = "priorities", EmitDefaultValue = true)]
        public List<WorkItemPriorityModel> Priorities { get; set; }

        /// <summary>
        /// Gets or Sets SourceTypes
        /// </summary>
        [DataMember(Name = "sourceTypes", EmitDefaultValue = true)]
        public List<WorkItemSourceTypeModel> SourceTypes { get; set; }

        /// <summary>
        /// Gets or Sets Types
        /// </summary>
        [DataMember(Name = "types", EmitDefaultValue = true)]
        public List<WorkItemTypeModel> Types { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public Int32RangeSelectorModel Duration { get; set; }

        /// <summary>
        /// Gets or Sets IsAutomated
        /// </summary>
        [DataMember(Name = "isAutomated", EmitDefaultValue = true)]
        public bool? IsAutomated { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets ExcludeTags
        /// </summary>
        [DataMember(Name = "excludeTags", EmitDefaultValue = true)]
        public List<string> ExcludeTags { get; set; }

        /// <summary>
        /// Gets or Sets AutoTestIds
        /// </summary>
        [DataMember(Name = "autoTestIds", EmitDefaultValue = true)]
        public List<Guid> AutoTestIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkItemFilterApiModel {\n");
            sb.Append("  NameOrId: ").Append(NameOrId).Append("\n");
            sb.Append("  IncludeIds: ").Append(IncludeIds).Append("\n");
            sb.Append("  ExcludeIds: ").Append(ExcludeIds).Append("\n");
            sb.Append("  ProjectIds: ").Append(ProjectIds).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("  GlobalIds: ").Append(GlobalIds).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  SectionIds: ").Append(SectionIds).Append("\n");
            sb.Append("  States: ").Append(States).Append("\n");
            sb.Append("  Priorities: ").Append(Priorities).Append("\n");
            sb.Append("  SourceTypes: ").Append(SourceTypes).Append("\n");
            sb.Append("  Types: ").Append(Types).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  IsAutomated: ").Append(IsAutomated).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  ExcludeTags: ").Append(ExcludeTags).Append("\n");
            sb.Append("  AutoTestIds: ").Append(AutoTestIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 0.", new [] { "Name" });
            }

            yield break;
        }
    }

}
