name: Pre-publish

on:
  pull_request

env:
  RUNNER_DIR: ./TmsRunner
  NUGET_DIR: ./nuget

jobs:
  build-pre-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          Tms.Adapter,
          Tms.Adapter.Core,
          Tms.Adapter.XUnit,
          Tms.Adapter.SpecFlowPlugin
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./${{ matrix.project }}

      - name: Build project
        run: |
          dotnet build --configuration Release \
          --no-restore ./${{ matrix.project }}

      - name: Create NuGet package
        run: |
          dotnet pack --configuration Release \
          --no-build --output ${{ env.NUGET_DIR }} \
          ./${{ matrix.project }}

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGet-package-${{ matrix.project }}
          path: ${{ env.NUGET_DIR }}/*.nupkg
  
  pre-publish:
    runs-on: ubuntu-latest
    needs: [ build-pre-publish ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: NuGet-package-*
          path: ${{ env.NUGET_DIR }}
          merge-multiple: true
      
      - name: Validate pre-publish
        run: |
          ls -a ${{ env.NUGET_DIR }}

 