name: Validate

on:
  pull_request


jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./Tms.Adapter,
          ./TmsRunner,
          ./Tms.Adapter.Core,
          ./Tms.Adapter.XUnit
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build --no-restore ${{ matrix.project }}
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./TmsRunnerTests,
          ./Tms.Adapter.CoreTests,
          ./Tms.Adapter.XUnitTests,
          ./Tms.Adapter.SpecFlowPluginTests,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Install coveralls.net
        run: dotnet tool install -g coveralls.net
        
      - name: Tests 
        run: | 
            dotnet test ${{ matrix.project }} --collect:"XPlat Code Coverage"
            coveralls.net --opencover -i ./coverage/coverage.opencover.xml --repo-token ${{ secrets.GITHUB_TOKEN }}
