name: Validate

on:
  pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./Tms.Adapter,
          ./TmsRunner,
          ./Tms.Adapter.Core,
          ./Tms.Adapter.XUnit
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build --no-restore ${{ matrix.project }}
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./TmsRunnerTests,
          ./Tms.Adapter.CoreTests
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet test ${{ matrix.project }}