name: Validate

on:
  pull_request

env:
  PROJECT_DIR: ./src/TestIt.Client
  VALIDATION: 1

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          ./Tms.Adapter,
          ./TmsRunner
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build --no-restore ${{ matrix.project }}
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./TmsRunnerTests

      - name: Build project
        run: dotnet test ./TmsRunnerTests